#!/usr/bin/env python

import sys

for arg in sys.argv:
    if "0x" in arg:
        hexNumber = remove_prefix(arg, "0x")
        length = len(hexNumber)
        # Initialize base to 1 (16x0)
        base = 1
        decNumber = 0
        for i in range(length - 1, -1, -1):
            if hexNumber[i] >= "0" and hexNumber[i] <= "9":
                decNumber += (ord(hexNumber[i]) - 48) * base

                base = base * 16

            elif hexNumber[i] >= "A" and hexNumber[i] <= "F":
                decNumber += (ord(hexNumber[i]) - 55) * base

                base = base * 16

        print(decNumber)

    def remove_prefix(text, prefix):
        if text.startswith(prefix):
            return text[len(prefix) :]
        return text
